version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
#!!!Don't hardcode secrets in your code!!!
      DATABASE_URL: postgresql://flaskuser:Pass.Flask@!@db:5432/flaskdb #flaskdb=dbname-flaskuser=dbusername
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: SECRET
      POSTGRES_PASSWORD: SECRET
      POSTGRES_DB: SECRET
